config/routes.rb
Rails.application.routes.draw do

  root "dashboards#index"

  devise_for :admin_users, :controllers => { :omniauth_callbacks => "admin_users/omniauth_callbacks" }
  resources :calendars do
    get :specific_list, on: :member
    get :specific_edit, on: :member
    put :specific_update, on: :member
  end
  resources :auth
  resources :dashboards do
    get :fetch_forecast, on: :collection
  end

  get 'callback', to: "auth#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/calendar.rb
class Calendar < ApplicationRecord

  validates :start_date, :end_date, :address, :car_number, presence: true

  after_create do |cal|
  end

  
  PERIOD_STR=[
    "충전",
    "주1회",
    "주2회"
  ]


  WEEKDAY_STR=[
    "월요일",
    "화요일",
    "수요일",
    "목요일",
    "금요일",
    "토요일",
    "일요일"
  ]

  def wash_recursive_str
    "#{PERIOD_STR[self.per_wash]} / #{WEEKDAY_STR[self.day_sel]}"
  end

  def dup_calendar
     calendar = self.dup
     calendar.calendar_id = nil
     calendar.start_date = calendar.end_date + 1.week
     calendar.end_date = calendar.start_date + 1.month
     calendar.calendar_response =nil
     calendar
  end

  def update_extend
    self.update_attributes(is_extend: 1)
  end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  before_action :authenticate_admin_user!
  before_action :set_calendar_auth, only: [:create, :update, :destroy, :specific_list, :specific_edit, :specific_update]

  def index
    @calendars = Calendar.page(params[:page]).per(params[:per])
    @soon_end_calendars = Calendar.where("calendars.is_extend = 0 and calendars.end_date <= ?",Date.current + 1.week)
  end

  def show
    @calendar = Calendar.find(params[:id])
  end

  def new
    @calendar = Calendar.new
    @calendar = Calendar.find(params[:extend_id]).dup_calendar if params[:extend_id].present?
  end

  def create

=begin
    e.start_time =  Time.parse("2017-03-29 14:00")
    e.end_time = Time.parse("2017-03-29 15:00")
    e.recurrence = {freq: "weekly", interval: 2,  until: Time.parse("20170717T130000Z") }
    e.title= "Sample Calendar"
    e.location = "용산구 한남동 123-4 "
    e.description = "정고객 010-2233-1234 벤츠"
=end

    @calendar = Calendar.new(calendar_param)


=begin
   begin

    @response = @cal.create_event do  |e|
      start_time = Time.parse("#{params[:do_start]} #{params[:time_sel]}")
      e.start_time = start_time
      e.end_time = start_time + 2.hours
      until_time = Time.parse("#{params[:do_until]} #{params[:time_sel]}")  + 2.hours
      case params[:per_wash]
      when "1"
        e.recurrence = {freq: "weekly", interval: 1,  until: until_time  }
      when "2"
        e.recurrence = {freq: "weekly", interval: 2,  until: until_time }
      end
      e.title= params[:name]
      e.location = params[:address]
      e.description = "#{params[:car_number]}, #{parmas[:wash_type]}, #{params[:memo]}"
    end

    redirect_to calendars_path(cal_id: @response.id)

   rescue
    render :action => 'new'
   end
=end

     @calendar.start_date = @calendar.start_date.beginning_of_week + @calendar.day_sel.to_i.days

     if @calendar.save

        Calendar.where(id: params[:extend_id]).first.update_extend if params[:extend_id].present?

        @cal = Google::Calendar.new(client_id: ENV['GOOGLE_API_CLIENT_ID'],
           :client_secret => ENV['GOOGLE_API_SECRET'],
           :calendar      => ENV['GOOGLE_CALENDAR_ID'],
           :redirect_url  => "#{OmniAuth.config.full_host}/admin_users/auth/google_oauth2/callback"
          )

        @cal.login_with_refresh_token(current_admin_user.refresh_token)

        @response = @cal.create_event do  |e|
          #start_time = Time.zone.parse("#{@calendar.start_date} #{@calendar.time_sel}+0900")
          #e.start_time = start_time
          # e.end_time = start_time + 2.hours
          #until_time = Time.zone.parse("#{@calendar.end_date} #{@calendar.time_sel}+0900")  + 2.hours

          start_date = Time.zone.parse("#{@calendar.start_date}")
          e.all_day = start_date
          until_date = Time.zone.parse("#{@calendar.end_date}")
          case @calendar.per_wash
          when 1
            e.recurrence = {freq: "weekly", interval: 1,  until: until_date }
          when 2
            e.recurrence = {freq: "weekly", interval: 2,  until: until_date }
          end
          e.title= @calendar.name
          e.location = @calendar.address
          e.description = "전화번호: #{@calendar.phone}\n#{@calendar.car_number}, #{@calendar.memo}"
        end

        @calendar.update_attributes(calendar_response: @response.raw, calendar_id: @response.raw["id"])

       redirect_to calendars_path
     else
       render :new
     end



  end

  def edit
    @calendar = Calendar.find(params[:id])
  end

  def update

    # Time.now.utc.strftime("%Y%m%dT%H%M%S")
    # @cal.find_event_by_id("884isjn66ger2qnvrjlmlk2o78_20170426T050000Z" )

    @calendar = Calendar.find(params[:id])

    if @calendar.update_attributes(calendar_param)


      @calendar.start_date = @calendar.start_date.beginning_of_week + @calendar.day_sel.to_i.days
      @response = @cal.find_or_create_event_by_id(@calendar.calendar_id) do  |e| 
        #start_time = Time.zone.parse("#{@calendar.start_date} #{@calendar.time_sel}+0900")
        #e.start_time = start_time
        #e.end_time = start_time + 2.hours
        #until_time = Time.zone.parse("#{@calendar.end_date} #{@calendar.time_sel}+0900")  + 2.hours

        start_date = Time.zone.parse("#{@calendar.start_date}")
        e.all_day = start_date
        until_date = Time.zone.parse("#{@calendar.end_date}")
        case @calendar.per_wash
        when 1
          e.recurrence = {freq: "weekly", interval: 1,  until: until_date  }
        when 2
          e.recurrence = {freq: "weekly", interval: 2,  until: until_date  }
        end
        e.title= @calendar.name
        e.location = @calendar.address
        e.description = "전화번호: #{@calendar.phone}\n#{@calendar.car_number}, #{@calendar.memo}"
      end

      @calendar.update_attributes(calendar_response: @response.raw )



      redirect_to calendars_path, :notice  => "Successfully updated calendar."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_url, :notice => "Successfully destroyed calendar."
  end

  def specific_list

    @calendar = Calendar.find(params[:id])
    cal_uid = eval(@calendar.calendar_response)["iCalUID"]
    @event_list =  @cal.find_events("&singleEvents=true&iCalUID=#{cal_uid}&orderBy=startTime")
  end

  def specific_edit
    @calendar = Calendar.find(params[:id])
    @event = @cal.find_event_by_id(params[:calendar_id]).first
    @info = @event.raw
    @time_custom = @info["start"]["dateTime"].present? &&  !["10:00","13:00","16:00"].include?(DateTime.parse(@info["start"]["dateTime"]).strftime("%H:%M"))

  end

  def specific_update
    @calendar = Calendar.find(params[:id])

    @response = @cal.find_or_create_event_by_id(params[:event_id]) do  |e|

      if params[:is_custom] == "1"
        start_time = Time.zone.parse("#{params[:start_date]} #{params[:time_sel_custom]}+0900")
        e.start_time = start_time
        e.end_time = start_time + 2.hours
      elsif params[:time_sel].present?
        start_time = Time.zone.parse("#{params[:start_date]} #{params[:time_sel]}+0900")
        e.start_time = start_time
        e.end_time = start_time + 2.hours
      else
        start_date = Time.zone.parse("#{params[:start_date]}")
        e.all_day = start_date
      end

      e.title = params[:name]
      e.location = params[:address]
      e.description = params[:description]
    end

   redirect_to specific_list_calendar_path(@calendar)



  end



  private
  def set_calendar_auth

    @cal = Google::Calendar.new(client_id: ENV['GOOGLE_API_CLIENT_ID'],
       :client_secret => ENV['GOOGLE_API_SECRET'],
       :calendar      => ENV['GOOGLE_CALENDAR_ID'],
       :redirect_url  => "#{OmniAuth.config.full_host}/admin_users/auth/google_oauth2/callback"
      )


    @cal.login_with_refresh_token(current_admin_user.refresh_token)
    current_admin_user.update_attributes(refresh_token: @cal.refresh_token) if @cal.refresh_token != current_admin_user.refresh_token

  end

  def calendar_param
    params.require(:calendar).permit(:name, :per_wash, :wash_type, :start_date, :end_date, :day_sel, :time_sel, :phone, :address, :car_number, :memo)
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for @calendar do |f| %>
  <%#= f.error_messages %>
  <%= hidden_field_tag :extend_id, params[:extend_id] %>

  <div class="form-group row">
    <%= f.label :name, "고객명", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control", placeholder: "고객명"  %>
    </div>
  </div>


  <div class="form-group row">
    <%= f.label :per_wash, "세차 주기", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.select :per_wash, options_for_select([['충전(1회)','0'],['1주 간격','1'],['2주 간격','2']], f.object.per_wash), {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :wash_type, "내외부", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.select :wash_type, options_for_select([['외부','0'],['내부','1'],['내외부','2']], f.object.wash_type),{}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :do_start, "시작일", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :start_date, class: "form-control", placeholder: Date.today.strftime("%Y-%m-%d") %>
    </div>
  </div>


  <div class="form-group row">
    <%= f.label :do_until, "마감일", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :end_date, class: "form-control", placeholder: Date.today.strftime("%Y-%m-%d")  %>
    </div>
 </div>

  <div class="form-group row">
    <%= f.label :day_sel, "요일", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.select :day_sel, options_for_select([['월요일','0'],['화요일','1'],['수요일','2'],['목요일','3'],['금요일','4'],['토요일','5'],['일요일','6']], f.object.day_sel),{} , class: "form-control" %>
      <%# Date.today.beginning_of_week => Monday %>
    </div>
  </div>

 
  <div class="form-group row">
    <% f.label :time_sel, "시간", class: "col-2 col-form-label" %>
    <div class="col-10">
      <% f.select :time_sel, options_for_select([['10:00','10:00'],['13:00','13:00'],['16:00','16:00']], (f.object.time_sel.strftime("%H:%M") if f.object.time_sel.present?)  ), {}, class: "form-control" %>
    </div>
  </div>

 
  <div class="form-group row">
    <%= f.label :phone, "전화번호", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :phone , class: "form-control", placeholder: "010-1234-5678" %>
    </div>
  </div>
 
  <div class="form-group row">
    <%= f.label :address, "주소", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :address, class: "form-control", placeholder: "서울시 강남구 ..." %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :car_number, "차량정보", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :car_number, class: "form-control", placeholder: "A5, 99허9999" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :memo, "기타사항", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_area :memo, class: "form-control", placeholder: "기타 기타 기타" %>
    </div>
  </div>


  <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit " Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<%= render 'form' %>

app/views/calendars/index.html.erb
<div class="search_form">
   <%= form_tag calendars_path, remote: true, class: "form-inline",  :method => :get  do %>
     <div class="form-group">
       <%= label_tag  :name, "고객명"  %>
       <%= text_field_tag :name, params[:name], :class => 'form-control'  %>
     </div>

     <%= submit_tag "Search", class: "btn btn-warning" %>
   <% end %>
</div>



<p><%= link_to "New Calendar", new_calendar_path, class: "btn btn-primary" %></p>

<% if @soon_end_calendars.present? %>
  <h3> 종료 임박 </h3>
  <table class="table table-hove">
     <tr>
      <th>고객명</th>
      <th>날짜</th>
      <th>기간</th>
      <th>주기</th>
      <th></th>
    </tr>
    <% for calendar in @soon_end_calendars %>
      <tr>
        <td><%= calendar.name %></td>
        <td><%= calendar.start_date.strftime("%Y-%m-%d") if calendar.start_date.present? %> ~ <%= calendar.end_date.strftime("%Y-%m-%d") if calendar.end_date.present? %></td>
        <td><%= calendar.wash_recursive_str %></td>
        <td>
          <%= link_to "개별 수정", specific_list_calendar_path(calendar), class: "btn btn-warning" %>
          <%= link_to "연장", new_calendar_path(extend_id: calendar), class: "btn btn-warning" %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<table class="table table-hove">
  <tr>
    <th>고객명</th>
    <th>날짜</th>
    <th>기간</th>
    <th>주기</th>
    <th></th>
  </tr>
  <% for calendar in @calendars %>
    <tr>
      <td><%= calendar.name %></td>
      <td><%= calendar.start_date.strftime("%Y-%m-%d") if calendar.start_date.present? %> ~ <%= calendar.end_date.strftime("%Y-%m-%d") if calendar.end_date.present? %></td>
      <td><%= calendar.wash_recursive_str %></td>
      <td>
        <%= link_to "개별 수정", specific_list_calendar_path(calendar), class: "btn btn-warning" %>
        <%= link_to "전체수정", edit_calendar_path(calendar), class: "btn btn-warning" %>
        <%= link_to "삭제", calendar, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-danger" %>
        <% link_to "연장", new_calendar_path(extend_id: calendar), class: "btn btn-warning" %>
      </td>
    </tr>
  <% end %>
</table>

<%= paginate @calendars %>

<p><%= link_to "New Calendar", new_calendar_path, class: "btn btn-primary" %></p>

app/views/calendars/new.html.erb
<%= render 'form' %>

app/views/calendars/show.html.erb
<% title "Calendar" %>

<p>
  <strong>Name:</strong>
  <%= @calendar.name %>
</p>

<p>
  <%= link_to "Edit", edit_calendar_path(@calendar) %> |
  <%= link_to "Destroy", @calendar, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", calendars_path %>
</p>

app/views/calendars/specific_edit.html.erb
<%= form_tag  specific_update_calendar_path(@calendar), method: :put do  %>
 
  <%= hidden_field_tag :event_id, @event.id %>

  <div class="form-group row">
    <%= label_tag :name, "고객명", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= text_field_tag :name, @info["summary"], class: "form-control", placeholder: "고객명"  %>
    </div>
  </div>

  <div class="form-group row">
    <%= label_tag :do_start, "시작일", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= text_field_tag :start_date, @info["start"]["date"], class: "form-control", placeholder: Date.today.strftime("%Y-%m-%d") if @info["start"]["date"].present? %>
      <%= text_field_tag :start_date, Date.parse(@info["start"]["dateTime"]).strftime("%Y-%m-%d"), class: "form-control", placeholder: Date.today.strftime("%Y-%m-%d") if @info["start"]["dateTime"].present?%>
    </div>
  </div>

  <div class="form-group row">
    <%= label_tag :time_sel, "시간", class: "col-2 col-form-label" %>
    <div class="col-10">
        <%= radio_button_tag :is_custom, 0, !@time_custom %>
        <%= select_tag :time_sel, options_for_select([['10:00','10:00'],['13:00','13:00'],['16:00','16:00']]), prompt: "선택", disabled: @time_custom, class: "form-control" %>
        <%= radio_button_tag :is_custom, 1, @time_custom%>
        <%= text_field_tag :time_sel_custom, @info["start"]["dateTime"].present?? DateTime.parse(@info["start"]["dateTime"]).strftime("%H:%M") : "", class: "form-control", placeholder: "09:00", disabled: !@time_custom %>
    </div>
  </div>

  <div class="form-group row">
    <%= label_tag :address, "주소", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= text_field_tag :address, @info["location"], class: "form-control", placeholder: "서울시 강남구 ..." %>
    </div>
  </div>

  <div class="form-group row">
    <%= label_tag :description, "기타사항", class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= text_area_tag :description, @info["description"], class: "form-control", placeholder: "기타 기타 기타" %>
    </div>
  </div>


  <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= submit_tag " Save", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/calendars/specific_list.html.erb
<table class="table table-hove">
  <tr>
    <th>고객명</th>
    <th>기간</th>
    <th>장소</th>
    <th></th>
  </tr>
  <% for event in @event_list%>
    <% info = event.raw %>
    <tr>
      <td><%= info["summary"] %></td>
      <td>
        <%= info["start"]["date"] if info["start"]["date"].present?  %>
        <%= "#{DateTime.parse(info["start"]["dateTime"]).strftime("%Y-%m-%d %H:%M")} ~  #{DateTime.parse(info["end"]["dateTime"]).strftime("%Y-%m-%d %H:%M")}"  if info["start"]["dateTime"].present? %>  </td>
      <td><%= info["location"] %></td>
      <td>
        <%= link_to "수정", specific_edit_calendar_path(@calendar, calendar_id: info["id"]), class: "btn btn-warning" %>
      </td>
    </tr>
  <% end %>
</table>