config/routes.rb
Rails.application.routes.draw do

  root "dashboards#index"

  devise_for :admin_users, :controllers => { :omniauth_callbacks => "admin_users/omniauth_callbacks" }
  resources :calendars do
    get :specific_list, on: :member
    get :specific_edit, on: :member
    put :specific_update, on: :member
  end
  resources :auth
  resources :dashboards do
    get :fetch_forecast, on: :collection
  end

  get 'callback', to: "auth#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to root_path do %>
    <%= image_tag "logo.png", size: '140x32', alt: "Logo" %>
  <% end %>
  <div class="collapse navbar-collapse" id="awash-header">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
          Home
          <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "캘린더", calendars_path,  class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu">
          <div class="dropdown-item">asdfasd</div>
          <div class="dropdown-divider"></div>
          <div class="dropdown-item">asdfasd</div>
        </div>
      </li>

    </ul>
    <% if current_admin_user.present? ||  Rails.env == "development" %>
      <div class="dropdown">
        <div class="dropdown-toggle user-status" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</div>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item">asdfasd</div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to destroy_admin_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>로그아웃</a>
              <% end %>
        </div>
        </div>
      </div>
    <% end %>

    <!--

    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" placeholder="Search" type="text">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwashSchedule</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', controller_name, media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', controller_name, 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if notice.present? %>
      <p class="notice alert alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
      </p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= alert %>
      </p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>